version: '3'

services:
  app:
    build: .
    depends_on:
      - selenium-chrome
    environment:
      - SELENIUM_URL=http://selenium-chrome:4444/wd/hub  # Selenium Chrome service URL

  selenium-chrome:
    # TODO: this image doesn't work on my m1 mac
    image: selenium/standalone-chrome:latest
    expose:
      - "4444"
